// The honesty page. What the deterministic engine decides versus what
// the model merely proposes, the defect distribution in the synthetic
// dataset, and the known limitation (split payments) stated plainly
// rather than hidden. Opens as a sheet from the sidebar footer so it
// stays reachable without occupying a nav slot.

export function MethodologyContent() {
  return (
    <div className="mt-6 space-y-6 text-sm leading-relaxed pb-10">
      <section>
        <h3 className="font-heading font-semibold mb-2">What the engine decides, what the model proposes</h3>
        <p className="text-muted-foreground mb-3">
          The rule this product is built around: the model never computes money. It listens,
          structures speech into events, and explains results. A deterministic engine calculates
          every rupee, posts every ledger entry, and decides every reconciliation match.
        </p>
        <table className="w-full text-xs border border-border">
          <thead>
            <tr className="bg-muted">
              <th className="text-left p-2 border-b border-border">Concern</th>
              <th className="text-left p-2 border-b border-border">Decided by</th>
            </tr>
          </thead>
          <tbody className="tabular-figures">
            {[
              ["Money calculation and ledger posting", "Deterministic code, always"],
              ["Reconciliation match decision", "Deterministic code, always"],
              ["Match confidence above 90%, the auto-post line", "Deterministic code, the model cannot cross it"],
              ["Ambiguous counterparty reasoning (72-90% band)", "Model proposes, capped at 89%, never auto-posted"],
              ["GST and tax arithmetic", "Deterministic code, always"],
              ["Cash forecast", "Deterministic recurrence model, not an LLM"],
              ["Speech understanding and explanation", "Model"],
            ].map(([concern, decider]) => (
              <tr key={concern} className="odd:bg-background even:bg-muted/40">
                <td className="p-2 border-b border-border align-top">{concern}</td>
                <td className="p-2 border-b border-border align-top">{decider}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section>
        <h3 className="font-heading font-semibold mb-2">The synthetic dataset</h3>
        <p className="text-muted-foreground">
          Every transaction here is generated by a seeded, deterministic script, documented in
          the repository, not real customer data. Defects are deliberately injected: exact
          matches, counterparty name variants, settlement lag, settlement fee deltas, duplicate
          records, missing records, unknown counterparties, incorrect GST on invoices, and
          split payments. The distribution is stated in the README so the match rate means
          something rather than being self-graded.
        </p>
      </section>

      <section>
        <h3 className="font-heading font-semibold mb-2">Known limitation, stated honestly</h3>
        <p className="text-muted-foreground">
          The three-layer matcher performs one-to-one matching by design. A settlement paid in
          two separate transfers cannot be resolved as a single match. A dedicated detector
          catches most of these and raises an honest split-payment exception rather than a wrong
          match or a silent miss, but this remains a stated limitation, not a solved problem.
        </p>
      </section>

      <section>
        <h3 className="font-heading font-semibold mb-2">Voice, and how a turn actually works</h3>
        <p className="text-muted-foreground">
          Voice is a listen, think, speak loop across two independently verified providers,
          Sarvam for speech in and speech out, Gemini for text reasoning and tool calls, not a
          single live audio socket. A turn moves through four visible stages, listening,
          transcribing, thinking, speaking, shown next to the voice button so a wait is always
          labelled rather than silent. Reasoning tries `gemini-3.6-flash` first, falls back to
          `gemini-3.7-flash` on a failure or an empty response, and only as a last resort falls
          through once more to a free OpenRouter model. Speaking over the agent stops playback
          immediately and opens a new turn.
        </p>
      </section>

      <section>
        <h3 className="font-heading font-semibold mb-2">What is simulated, what is real</h3>
        <p className="text-muted-foreground">
          No live UPI rails, no NPCI membership, no Account Aggregator access, no bank core write
          access. Only a regulated entity can transact on those rails. This demo simulates
          the reconciliation loop against documented synthetic bank, UPI and invoice data. Not an
          accounting system of record and not tax advice.
        </p>
      </section>

      <section>
        <h3 className="font-heading font-semibold mb-2">Sign-in</h3>
        <p className="text-muted-foreground">
          This build runs as a single demo merchant with no login. The store layer already
          takes and checks an owner id on every read and write, so real authentication is a
          change to one function rather than a change to every call site later.
        </p>
      </section>
    </div>
  );
}
